### PR TITLE
Gist to script + dockerfile from plain ubuntu

### PR DESCRIPTION
**Pull request by almahmoud**
Not yet fully tested, but figured there is enough to make it visible to begin to get feedback

### CODE REVIEW

**Comment by jwokaty** [comment]
This looks pretty good.

**Comment by almahmoud** [comment]
I think the startfile trickery works well now, to have `R` be the entrypoint in a way that is version-independent.
This now works, tested with 1) `docker run --rm ghcr.io/almahmoud/bioconductor_salt:jammy-r-4.3.1 --version`, which successfully prints out R version, and 2) `docker run -it --rm ghcr.io/almahmoud/bioconductor_salt:jammy-r-4.3.1` which opens an R shell as `biocbuild` user. Finally, 3) a bash entrypoint also inherits the R path via `bashrc`
```
$ docker run -it --rm --entrypoint /bin/bash ghcr.io/almahmoud/bioconductor_salt:jammy-r-4.3.1
biocbuild@55605d4eb442:~$ which R
/home/biocbuild/bbs-3.18-bioc/R/bin/R
```

**Comment by jwokaty** [comment]
I think this is okay to merge unless there's anything more you want to add right now.

**Comment by jwokaty** [comment]
When running `docker build`, the output was clipped (2mb limit) when R was getting installed. Is there a way to increase the log limit?

This is a note for myself, but if users might run this on their laptop for whatever reason, it might be nice to change the number of cores used to compile R since my laptop threatens to seize with the default, which is to use all cores.

I think your code looks pretty good and I'm able to use the R and bash entrypoints, which do work well! I do see more problems with the configured state of the container, though, such as the pip modules not being installed.

**Comment by almahmoud** [comment]
Assuming you are using a relatively new version of `docker` with BuildKit enabled, I believe you'd need to do `--driver-opt env.BUILDKIT_STEP_LOG_MAX_SIZE=10485760`

Re users rebuilding, while some power users might want to modify the Dockerfile and rebuild, I would think most people would just use the container that gets automatically built by us on a schedule, rather than rebuild themselves. Also, if they fork the repository and make changes, a container will also be built within their fork in actions, which is likely the easiest way to modify and rebuild rather than a local build. With that said, I agree we should still make sure it's buildable on most machines as well if it's not too much effort.

Re missing pip modules, I am not sure where to start debugging, let's maybe discuss today

**Comment by jwokaty** [comment]
The issues I see are related to salt formulas failing. I am troubleshooting them. Still I don't see problems with your code.

**Comment by jwokaty** [comment]
I'm still fixing the salt, but it's a separate issue from your PR, which is good. Maybe it could use a little documentation in the README (before [vagrant stuff)](https://github.com/Bioconductor/bioconductor_salt#salted-vagrant) or where you think appropriate? I think I can merge it to the standalone branch soon. I am going to evaluate the standalone branch to determine if I can merge into main after I merge your work.

**Pull request merged**
